# Streamlit secrets.toml
# This file contains sensitive configuration for deployment
# DO NOT commit this file to version control

[watsonx]
api_key = "89B_QQncoXf53DaBc89zWwMpEvJ5lGfUoZ15eJuI7LaA"
project_id = "f7f03912-3bc3-43b1-9c1f-bcfb805ec438"
url = "https://eu-de.ml.cloud.ibm.com"
model_id = "ibm/granite-3-3-8b-instruct"
