# Streamlit secrets.toml
# This file contains sensitive configuration for deployment
# DO NOT commit this file to version control

[watsonx]
api_key = ""
project_id = ""
url = "https://eu-de.ml.cloud.ibm.com"
model_id = "ibm/granite-3-3-8b-instruct"
